apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    uid: postgres-app-db
    url: db:5432
    database: ${GRAFANA_DB_NAME}
    user: ${GRAFANA_DB_USER}
    isDefault: true
    jsonData:
      database: ${GRAFANA_DB_NAME}
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
