name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Cache uv environment
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}

      - name: Sync dependencies
        run: uv sync

      - name: Lint (ruff)
        run: |
          uv run ruff --version
          uv run ruff check .

      - name: Run tests (pytest)
        run: |
          uv run pytest
